/* ============================================
   architectures.js
   CPU Architecture Definitions
   Defines registers, instruction sets, memory
   layout for x86, x86_64, arm32, arm64
   ============================================ */

const Architectures = {
    x86: {
        name: 'x86',
        displayName: 'x86 (32-bit)',
        bits: 32,
        ptrSize: 4,
        wordSize: 4,
        stackAlignment: 4,
        callConvention: 'cdecl',
        endianness: 'little',

        registers: [
            { name: 'EAX',  desc: 'Accumulator',           role: 'general',  size: 4 },
            { name: 'EBX',  desc: 'Base',                  role: 'general',  size: 4 },
            { name: 'ECX',  desc: 'Counter',               role: 'general',  size: 4 },
            { name: 'EDX',  desc: 'Data',                  role: 'general',  size: 4 },
            { name: 'ESI',  desc: 'Source Index',          role: 'general',  size: 4 },
            { name: 'EDI',  desc: 'Destination Index',     role: 'general',  size: 4 },
            { name: 'EBP',  desc: 'Base Pointer',          role: 'bp',       size: 4 },
            { name: 'ESP',  desc: 'Stack Pointer',         role: 'sp',       size: 4 },
            { name: 'EIP',  desc: 'Instruction Pointer',   role: 'pc',       size: 4 },
            { name: 'EFLAGS', desc: 'Flags',               role: 'flags',    size: 4 },
        ],

        stackRegister: 'ESP',
        bpRegister: 'EBP',
        pcRegister: 'EIP',
        returnRegister: 'EAX',

        stackBase: 0x7FFFFF00,
        stackTop:  0x80000000,
        codeBase:  0x08048000,
        dataBase:  0x08049000,
        heapBase:  0x0804A000,
        heapTop:   0x09000000,

        instructionFormat: 'att',
        commentChar: '#',
        labelSuffix: ':',
        indentSize: 12,

        instructions: {
            MOV:   { operands: 2, desc: 'Move data' },
            ADD:   { operands: 2, desc: 'Add' },
            SUB:   { operands: 2, desc: 'Subtract' },
            MUL:   { operands: 1, desc: 'Multiply' },
            DIV:   { operands: 1, desc: 'Divide' },
            PUSH:  { operands: 1, desc: 'Push to stack' },
            POP:   { operands: 1, desc: 'Pop from stack' },
            CMP:   { operands: 2, desc: 'Compare' },
            JMP:   { operands: 1, desc: 'Jump' },
            JE:    { operands: 1, desc: 'Jump if equal' },
            JNE:   { operands: 1, desc: 'Jump if not equal' },
            JL:    { operands: 1, desc: 'Jump if less' },
            JG:    { operands: 1, desc: 'Jump if greater' },
            JLE:   { operands: 1, desc: 'Jump if less or equal' },
            JGE:   { operands: 1, desc: 'Jump if greater or equal' },
            CALL:  { operands: 1, desc: 'Call function' },
            RET:   { operands: 0, desc: 'Return' },
            LEA:   { operands: 2, desc: 'Load effective address' },
            AND:   { operands: 2, desc: 'Bitwise AND' },
            OR:    { operands: 2, desc: 'Bitwise OR' },
            XOR:   { operands: 2, desc: 'Bitwise XOR' },
            SHL:   { operands: 2, desc: 'Shift left' },
            SHR:   { operands: 2, desc: 'Shift right' },
            INC:   { operands: 1, desc: 'Increment' },
            DEC:   { operands: 1, desc: 'Decrement' },
            NEG:   { operands: 1, desc: 'Negate' },
            NOT:   { operands: 1, desc: 'Bitwise NOT' },
            TEST:  { operands: 2, desc: 'Test bits' },
            NOP:   { operands: 0, desc: 'No operation' },
            INT:   { operands: 1, desc: 'Interrupt' },
            LEAVE: { operands: 0, desc: 'Restore stack frame' },
        },

        callingConv: {
            argRegisters: [],
            calleeSave: ['EBX', 'ESI', 'EDI', 'EBP'],
            callerSave: ['EAX', 'ECX', 'EDX'],
            stackCleanup: 'caller',
        },
    },

    x86_64: {
        name: 'x86_64',
        displayName: 'x86_64 (64-bit)',
        bits: 64,
        ptrSize: 8,
        wordSize: 8,
        stackAlignment: 16,
        callConvention: 'SystemV',
        endianness: 'little',

        registers: [
            { name: 'RAX',  desc: 'Accumulator / Return',     role: 'general',  size: 8 },
            { name: 'RBX',  desc: 'Base',                     role: 'general',  size: 8 },
            { name: 'RCX',  desc: 'Counter / Arg4',           role: 'general',  size: 8 },
            { name: 'RDX',  desc: 'Data / Arg3',              role: 'general',  size: 8 },
            { name: 'RSI',  desc: 'Source / Arg2',            role: 'general',  size: 8 },
            { name: 'RDI',  desc: 'Destination / Arg1',       role: 'general',  size: 8 },
            { name: 'RBP',  desc: 'Base Pointer',             role: 'bp',       size: 8 },
            { name: 'RSP',  desc: 'Stack Pointer',            role: 'sp',       size: 8 },
            { name: 'R8',   desc: 'Arg5',                     role: 'general',  size: 8 },
            { name: 'R9',   desc: 'Arg6',                     role: 'general',  size: 8 },
            { name: 'R10',  desc: 'General / Syscall',        role: 'general',  size: 8 },
            { name: 'R11',  desc: 'General / Syscall',        role: 'general',  size: 8 },
            { name: 'R12',  desc: 'Callee Saved',             role: 'general',  size: 8 },
            { name: 'R13',  desc: 'Callee Saved',             role: 'general',  size: 8 },
            { name: 'R14',  desc: 'Callee Saved',             role: 'general',  size: 8 },
            { name: 'R15',  desc: 'Callee Saved',             role: 'general',  size: 8 },
            { name: 'RIP',  desc: 'Instruction Pointer',      role: 'pc',       size: 8 },
            { name: 'RFLAGS', desc: 'Flags Register',         role: 'flags',    size: 8 },
        ],

        stackRegister: 'RSP',
        bpRegister: 'RBP',
        pcRegister: 'RIP',
        returnRegister: 'RAX',

        stackBase: 0x7FFFFFFFEFF0,
        stackTop:  0x800000000000,
        codeBase:  0x400000,
        dataBase:  0x600000,
        heapBase:  0x601000,
        heapTop:   0x700000,

        instructionFormat: 'att',
        commentChar: '#',
        labelSuffix: ':',
        indentSize: 12,

        instructions: {
            MOV:   { operands: 2, desc: 'Move data' },
            ADD:   { operands: 2, desc: 'Add' },
            SUB:   { operands: 2, desc: 'Subtract' },
            IMUL:  { operands: 2, desc: 'Multiply' },
            IDIV:  { operands: 1, desc: 'Divide' },
            PUSH:  { operands: 1, desc: 'Push to stack' },
            POP:   { operands: 1, desc: 'Pop from stack' },
            CMP:   { operands: 2, desc: 'Compare' },
            JMP:   { operands: 1, desc: 'Jump' },
            JE:    { operands: 1, desc: 'Jump if equal' },
            JNE:   { operands: 1, desc: 'Jump if not equal' },
            JL:    { operands: 1, desc: 'Jump if less' },
            JG:    { operands: 1, desc: 'Jump if greater' },
            JLE:   { operands: 1, desc: 'Jump if less or equal' },
            JGE:   { operands: 1, desc: 'Jump if greater or equal' },
            CALL:  { operands: 1, desc: 'Call function' },
            RET:   { operands: 0, desc: 'Return' },
            LEA:   { operands: 2, desc: 'Load effective address' },
            AND:   { operands: 2, desc: 'Bitwise AND' },
            OR:    { operands: 2, desc: 'Bitwise OR' },
            XOR:   { operands: 2, desc: 'Bitwise XOR' },
            SHL:   { operands: 2, desc: 'Shift left' },
            SHR:   { operands: 2, desc: 'Shift right' },
            INC:   { operands: 1, desc: 'Increment' },
            DEC:   { operands: 1, desc: 'Decrement' },
            NEG:   { operands: 1, desc: 'Negate' },
            NOT:   { operands: 1, desc: 'Bitwise NOT' },
            TEST:  { operands: 2, desc: 'Test bits' },
            NOP:   { operands: 0, desc: 'No operation' },
            INT:   { operands: 1, desc: 'Interrupt' },
            LEAVE: { operands: 0, desc: 'Restore stack frame' },
        },

        callingConv: {
            argRegisters: ['RDI', 'RSI', 'RDX', 'RCX', 'R8', 'R9'],
            calleeSave: ['RBX', 'RBP', 'R12', 'R13', 'R14', 'R15'],
            callerSave: ['RAX', 'RCX', 'RDX', 'RSI', 'RDI', 'R8', 'R9', 'R10', 'R11'],
            stackCleanup: 'caller',
        },
    },

    arm32: {
        name: 'arm32',
        displayName: 'ARM (32-bit)',
        bits: 32,
        ptrSize: 4,
        wordSize: 4,
        stackAlignment: 8,
        callConvention: 'AAPCS',
        endianness: 'little',

        registers: [
            { name: 'R0',   desc: 'Arg1 / Return',           role: 'general',  size: 4 },
            { name: 'R1',   desc: 'Arg2',                    role: 'general',  size: 4 },
            { name: 'R2',   desc: 'Arg3',                    role: 'general',  size: 4 },
            { name: 'R3',   desc: 'Arg4',                    role: 'general',  size: 4 },
            { name: 'R4',   desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R5',   desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R6',   desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R7',   desc: 'Frame Pointer',           role: 'bp',       size: 4 },
            { name: 'R8',   desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R9',   desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R10',  desc: 'Callee Saved',            role: 'general',  size: 4 },
            { name: 'R11',  desc: 'Frame Pointer (alt)',     role: 'general',  size: 4 },
            { name: 'R12',  desc: 'Intra-procedure scratch', role: 'general',  size: 4 },
            { name: 'SP',   desc: 'Stack Pointer',           role: 'sp',       size: 4 },
            { name: 'LR',   desc: 'Link Register',           role: 'general',  size: 4 },
            { name: 'PC',   desc: 'Program Counter',         role: 'pc',       size: 4 },
            { name: 'CPSR', desc: 'Current Program Status',  role: 'flags',    size: 4 },
        ],

        stackRegister: 'SP',
        bpRegister: 'R7',
        pcRegister: 'PC',
        returnRegister: 'R0',
        linkRegister: 'LR',

        stackBase: 0x7FFFFF00,
        stackTop:  0x80000000,
        codeBase:  0x00010000,
        dataBase:  0x00020000,
        heapBase:  0x00030000,
        heapTop:   0x00100000,

        instructionFormat: 'arm',
        commentChar: ';',
        labelSuffix: ':',
        indentSize: 8,

        instructions: {
            MOV:   { operands: 2, desc: 'Move' },
            MVN:   { operands: 2, desc: 'Move NOT' },
            ADD:   { operands: 3, desc: 'Add' },
            SUB:   { operands: 3, desc: 'Subtract' },
            MUL:   { operands: 3, desc: 'Multiply' },
            MLA:   { operands: 4, desc: 'Multiply-Accumulate' },
            SDIV:  { operands: 3, desc: 'Divide' },
            AND:   { operands: 3, desc: 'Bitwise AND' },
            ORR:   { operands: 3, desc: 'Bitwise OR' },
            EOR:   { operands: 3, desc: 'Bitwise XOR' },
            LSL:   { operands: 3, desc: 'Logical shift left' },
            LSR:   { operands: 3, desc: 'Logical shift right' },
            CMP:   { operands: 2, desc: 'Compare' },
            CMN:   { operands: 2, desc: 'Compare negative' },
            TST:   { operands: 2, desc: 'Test bits' },
            LDR:   { operands: 2, desc: 'Load register' },
            STR:   { operands: 2, desc: 'Store register' },
            LDM:   { operands: 2, desc: 'Load multiple' },
            STM:   { operands: 2, desc: 'Store multiple' },
            PUSH:  { operands: 1, desc: 'Push registers' },
            POP:   { operands: 1, desc: 'Pop registers' },
            B:     { operands: 1, desc: 'Branch' },
            BL:    { operands: 1, desc: 'Branch with link' },
            BX:    { operands: 1, desc: 'Branch and exchange' },
            BEQ:   { operands: 1, desc: 'Branch if equal' },
            BNE:   { operands: 1, desc: 'Branch if not equal' },
            BLT:   { operands: 1, desc: 'Branch if less than' },
            BGT:   { operands: 1, desc: 'Branch if greater than' },
            BLE:   { operands: 1, desc: 'Branch if less or equal' },
            BGE:   { operands: 1, desc: 'Branch if greater or equal' },
            NOP:   { operands: 0, desc: 'No operation' },
            SVC:   { operands: 1, desc: 'Supervisor call' },
        },

        callingConv: {
            argRegisters: ['R0', 'R1', 'R2', 'R3'],
            calleeSave: ['R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11'],
            callerSave: ['R0', 'R1', 'R2', 'R3', 'R12'],
            stackCleanup: 'caller',
        },
    },

    arm64: {
        name: 'arm64',
        displayName: 'ARM64 (AArch64)',
        bits: 64,
        ptrSize: 8,
        wordSize: 8,
        stackAlignment: 16,
        callConvention: 'AAPCS64',
        endianness: 'little',

        registers: [
            { name: 'X0',   desc: 'Arg1 / Return',           role: 'general',  size: 8 },
            { name: 'X1',   desc: 'Arg2',                    role: 'general',  size: 8 },
            { name: 'X2',   desc: 'Arg3',                    role: 'general',  size: 8 },
            { name: 'X3',   desc: 'Arg4',                    role: 'general',  size: 8 },
            { name: 'X4',   desc: 'Arg5',                    role: 'general',  size: 8 },
            { name: 'X5',   desc: 'Arg6',                    role: 'general',  size: 8 },
            { name: 'X6',   desc: 'Arg7',                    role: 'general',  size: 8 },
            { name: 'X7',   desc: 'Arg8',                    role: 'general',  size: 8 },
            { name: 'X8',   desc: 'Indirect result',         role: 'general',  size: 8 },
            { name: 'X9',   desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X10',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X11',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X12',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X13',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X14',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X15',  desc: 'Caller Saved',            role: 'general',  size: 8 },
            { name: 'X16',  desc: 'IP0 / PLT',               role: 'general',  size: 8 },
            { name: 'X17',  desc: 'IP1 / PLT',               role: 'general',  size: 8 },
            { name: 'X18',  desc: 'Platform Register',       role: 'general',  size: 8 },
            { name: 'X19',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X20',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X21',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X22',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X23',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X24',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X25',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X26',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X27',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'X28',  desc: 'Callee Saved',            role: 'general',  size: 8 },
            { name: 'FP',   desc: 'Frame Pointer',           role: 'bp',       size: 8 },
            { name: 'LR',   desc: 'Link Register',           role: 'general',  size: 8 },
            { name: 'SP',   desc: 'Stack Pointer',           role: 'sp',       size: 8 },
            { name: 'PC',   desc: 'Program Counter',         role: 'pc',       size: 8 },
            { name: 'NZCV', desc: 'Condition Flags',         role: 'flags',    size: 4 },
        ],

        stackRegister: 'SP',
        bpRegister: 'FP',
        pcRegister: 'PC',
        returnRegister: 'X0',
        linkRegister: 'LR',

        stackBase: 0x7FFFFFFFEFF0,
        stackTop:  0x800000000000,
        codeBase:  0x400000,
        dataBase:  0x600000,
        heapBase:  0x601000,
        heapTop:   0x700000,

        instructionFormat: 'arm',
        commentChar: ';',
        labelSuffix: ':',
        indentSize: 8,

        instructions: {
            MOV:   { operands: 2, desc: 'Move' },
            MOVZ:  { operands: 3, desc: 'Move with zero' },
            MOVK:  { operands: 3, desc: 'Move with keep' },
            ADD:   { operands: 3, desc: 'Add' },
            SUB:   { operands: 3, desc: 'Subtract' },
            MUL:   { operands: 3, desc: 'Multiply' },
            MADD:  { operands: 4, desc: 'Multiply-Add' },
            SDIV:  { operands: 3, desc: 'Signed divide' },
            UDIV:  { operands: 3, desc: 'Unsigned divide' },
            AND:   { operands: 3, desc: 'Bitwise AND' },
            ORR:   { operands: 3, desc: 'Bitwise OR' },
            EOR:   { operands: 3, desc: 'Bitwise XOR' },
            LSL:   { operands: 3, desc: 'Logical shift left' },
            LSR:   { operands: 3, desc: 'Logical shift right' },
            CMP:   { operands: 2, desc: 'Compare' },
            CMN:   { operands: 2, desc: 'Compare negative' },
            TST:   { operands: 2, desc: 'Test bits' },
            LDR:   { operands: 2, desc: 'Load register' },
            STR:   { operands: 2, desc: 'Store register' },
            LDP:   { operands: 3, desc: 'Load pair' },
            STP:   { operands: 3, desc: 'Store pair' },
            PUSH:  { operands: 1, desc: 'Push registers' },
            POP:   { operands: 1, desc: 'Pop registers' },
            B:     { operands: 1, desc: 'Branch' },
            BL:    { operands: 1, desc: 'Branch with link' },
            BR:    { operands: 1, desc: 'Branch to register' },
            RET:   { operands: 0, desc: 'Return' },
            B_EQ:  { operands: 1, desc: 'Branch if equal' },
            B_NE:  { operands: 1, desc: 'Branch if not equal' },
            B_LT:  { operands: 1, desc: 'Branch if less than' },
            B_GT:  { operands: 1, desc: 'Branch if greater than' },
            B_LE:  { operands: 1, desc: 'Branch if less or equal' },
            B_GE:  { operands: 1, desc: 'Branch if greater or equal' },
            NOP:   { operands: 0, desc: 'No operation' },
            SVC:   { operands: 1, desc: 'Supervisor call' },
        },

        callingConv: {
            argRegisters: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7'],
            calleeSave: ['X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'FP'],
            callerSave: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18'],
            stackCleanup: 'caller',
        },
    },
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = Architectures;
}
